name: ReactNative CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
      working-directory: frontend
    - name: Install expo
      run: npm install expo
      working-directory: frontend
    - name: Run tests
      run: npm test
      working-directory: frontend
    - name: Build app
      run: npx expo build:web
      working-directory: frontend
